#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=${SCRIPT_DIR}/..

PIP_VIRTUAL_ENV_NAME="venv"
PIP_VIRTUAL_ENV_DIR=${ROOT_DIR}/${PIP_VIRTUAL_ENV_NAME}

NODEJS_VIRTUAL_ENV_NAME="nenv"
NODEJS_VIRTUAL_ENV_DIR=${ROOT_DIR}/${NODEJS_VIRTUAL_ENV_NAME}

TEMP_NAME="temp"
TEMP_DIR=${ROOT_DIR}/${TEMP_NAME}

